### ISSUE TITLE
Create tmp files in OBJ_DIR not L4_DIR

### ISSUE THREAD

**Issue by chelmuth** [ssumpf/foc#15]

**Comment by chelmuth** [comment]
Please merge at will (and don't forget to update Genode port).

**Comment by ssumpf** [comment]
@chelmuth: Done, please add https://github.com/ssumpf/genode/commit/31cad2e13dc753ae0f2452a9789f767d381bd73b to staging.

**Comment by chelmuth** [comment]
Seems fixed.
